{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- if .Values.env.PROVIDER_API_KEY }}
  PROVIDER_API_KEY: {{ .Values.env.PROVIDER_API_KEY | b64enc }}
  {{- end }}
{{- end }}
